### ISSUE TITLE
Update error: existing DB index

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/manualcrop#11]
I had an error when trying to update this module. It looks like there's an update hook that tries to add a `vid` index, but it already exists (and from what I can see it's always existed since the initial Drupal port, so not sure why it's needed...).

**Comment by ghost** [comment]
Error details:

manualcrop module
Update #1001
Failed: DatabaseSchemaObjectExistsException: Cannot add index vid to table manualcrop: index already exists. in DatabaseSchema_mysql->addIndex() (line 443 of /[SNIP]/core/includes/database/mysql/schema.inc).

**Comment by ghost** [comment]
Ok, so it seems that in https://git.drupalcode.org/project/manualcrop/blob/7.x-1.x/manualcrop.install#L349 the `vid` field was added and they updated the primary key, but not the index. So they then updated the index in https://git.drupalcode.org/project/manualcrop/blob/7.x-1.x/manualcrop.install#L460 which is what was copied to Backdrop.

**Comment by ghost** [comment]
This [PR](https://github.com/backdrop-contrib/manualcrop/pull/12) fixes the issue by first dropping the index if it exists so it can then (re)add it (similar to how core [Redirect module](https://api.backdropcms.org/api/backdrop/core%21modules%21redirect%21redirect.install/function/redirect_update_1001/1) does it).

**Comment by laryn** [comment]
Thanks @BWPanda!
