### ISSUE TITLE
Undefined variable: file_entity_vars in manualcrop_update_1000()

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/manualcrop#16]
I'm getting this error when upgrading a D7 site:

```
Undefined variable: file_entity_vars in manualcrop_update_1000() (line 177 of /[SNIP]/modules/manualcrop/manualcrop.install).
```

This is because `$file_entity_vars` is only set when the `file_entity` module exists, but it's used later outside of that `if` statement. So it needs to be set initially to an empty string.

**Comment by ghost** [comment]
PR: https://github.com/backdrop-contrib/manualcrop/pull/17

**Comment by laryn** [comment]
Thanks @BWPanda
