### ISSUE TITLE
ArgumentCountError for image_effect_delete()

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/manualcrop#18]
When deleting a manualcrop-enabled image style, I got this error message:

> ArgumentCountError: Too few arguments to function image_effect_delete(), 1 passed in .../modules/manualcrop/manualcrop.helpers.inc on line 999 and exactly 2 expected.`

**Comment by laryn** [comment]
@BWPanda Does this fix it for you? 

https://github.com/backdrop-contrib/manualcrop/compare/issue-18?expand=1

Based on [image_effect_delete](https://api.backdropcms.org/api/backdrop/core%21modules%21image%21image.module/function/image_effect_delete/1)

**Comment by ghost** [comment]
I can't remember where I saw this, but I trust you :smiley: Looks good.

**Comment by laryn** [comment]
So, this is not fixed yet. I managed to reproduce the error as follows:

 - Create an image style with a manual crop effect
 - Create a second image style with a "reuse manual crop" effect that reuses the first style
 - Delete the first image style

The PR does prevent the error but it seems to leave an empty image style behind:
![Screen Shot 2020-11-06 at 12 42 18 PM](https://user-images.githubusercontent.com/871421/98402817-88763f00-202d-11eb-9dd7-c5b66b730a8d.jpg)

This corresponds to a config file like this:
```
{
    "_config_name": "image.style.crop",
    "effects": null
}

```
